/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "Helpers/logger.h"
#include "usbd_framework.h"
#include "usb_device.h"

UsbDevice usb_device;
uint32_t buffer[8];

int main(void)
{
	log_info("Program entry point.");

	usb_device.ptr_out_buffer = &buffer;

	usbd_initialize(&usb_device);

    /* Loop forever */
	for(;;)
	{
		usbd_poll();

	}
}
